name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Project
      run: sudo apt-get install -y libsqlite3-dev && bundle install && bundle exec rails db:migrate
    - name: Run Unit Tests
      run: rails test
